# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vis.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1297, 869)
        Form.setStyleSheet("")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(50, 130, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label1.setFont(font)
        self.label1.setTextFormat(QtCore.Qt.AutoText)
        self.label1.setObjectName("label1")
        self.cam_num = QtWidgets.QComboBox(Form)
        self.cam_num.setGeometry(QtCore.QRect(50, 150, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.cam_num.setFont(font)
        self.cam_num.setObjectName("cam_num")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.cam_num.addItem("")
        self.label2 = QtWidgets.QLabel(Form)
        self.label2.setGeometry(QtCore.QRect(50, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.startFrame = QtWidgets.QComboBox(Form)
        self.startFrame.setGeometry(QtCore.QRect(50, 220, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.startFrame.setFont(font)
        self.startFrame.setObjectName("startFrame")
        self.startFrame.addItem("")
        self.label3 = QtWidgets.QLabel(Form)
        self.label3.setGeometry(QtCore.QRect(50, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.endFrame = QtWidgets.QComboBox(Form)
        self.endFrame.setGeometry(QtCore.QRect(50, 300, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.endFrame.setFont(font)
        self.endFrame.setObjectName("endFrame")
        self.endFrame.addItem("")
        self.endFrame.addItem("")
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setGeometry(QtCore.QRect(50, 450, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.okButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/confirm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon)
        self.okButton.setObjectName("okButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 760, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.startButton = QtWidgets.QPushButton(Form)
        self.startButton.setGeometry(QtCore.QRect(50, 490, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.startButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.stopButton = QtWidgets.QPushButton(Form)
        self.stopButton.setGeometry(QtCore.QRect(50, 530, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.stopButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/data/qrc/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.lefttop_widget = QtWidgets.QWidget(Form)
        self.lefttop_widget.setGeometry(QtCore.QRect(30, 90, 151, 341))
        self.lefttop_widget.setObjectName("lefttop_widget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.lefttop_widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 151, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.lefttop_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.lefttop_Layout.setContentsMargins(0, 0, 0, 0)
        self.lefttop_Layout.setObjectName("lefttop_Layout")
        self.leftdown_widget = QtWidgets.QWidget(Form)
        self.leftdown_widget.setGeometry(QtCore.QRect(30, 440, 151, 151))
        self.leftdown_widget.setObjectName("leftdown_widget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.leftdown_widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 151, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.leftdown_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.leftdown_Layout.setContentsMargins(0, 0, 0, 0)
        self.leftdown_Layout.setObjectName("leftdown_Layout")
        self.right_widget = QtWidgets.QWidget(Form)
        self.right_widget.setGeometry(QtCore.QRect(200, 20, 1001, 781))
        self.right_widget.setObjectName("right_widget")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.right_widget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 1001, 781))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.right_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.right_Layout.setContentsMargins(1, 1, 1, 1)
        self.right_Layout.setSpacing(3)
        self.right_Layout.setObjectName("right_Layout")
        self.videoBox = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox.setText("")
        self.videoBox.setObjectName("videoBox")
        self.right_Layout.addWidget(self.videoBox, 1, 0, 1, 1)
        self.videoBox_heatmap = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox_heatmap.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox_heatmap.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox_heatmap.setText("")
        self.videoBox_heatmap.setObjectName("videoBox_heatmap")
        self.right_Layout.addWidget(self.videoBox_heatmap, 2, 0, 1, 1)
        self.videoBox_traj = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.videoBox_traj.setBaseSize(QtCore.QSize(0, 0))
        self.videoBox_traj.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.videoBox_traj.setText("")
        self.videoBox_traj.setObjectName("videoBox_traj")
        self.right_Layout.addWidget(self.videoBox_traj, 1, 2, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget_3)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(0, 30, 991, 691))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.tab_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.tab_Layout.setContentsMargins(0, 0, 0, 0)
        self.tab_Layout.setObjectName("tab_Layout")
        self.subtab_widget = QtWidgets.QWidget(self.gridLayoutWidget_7)
        self.subtab_widget.setObjectName("subtab_widget")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.subtab_widget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, 991, 721))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.subtab_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.subtab_Layout.setContentsMargins(0, 0, 0, 0)
        self.subtab_Layout.setObjectName("subtab_Layout")
        self.tab_Layout.addWidget(self.subtab_widget, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cam1_box = QtWidgets.QLabel(self.tab_2)
        self.cam1_box.setGeometry(QtCore.QRect(20, 20, 330, 160))
        self.cam1_box.setText("")
        self.cam1_box.setObjectName("cam1_box")
        self.cam3_box = QtWidgets.QLabel(self.tab_2)
        self.cam3_box.setGeometry(QtCore.QRect(60, 370, 330, 160))
        self.cam3_box.setText("")
        self.cam3_box.setObjectName("cam3_box")
        self.cam2_box = QtWidgets.QLabel(self.tab_2)
        self.cam2_box.setGeometry(QtCore.QRect(20, 210, 330, 160))
        self.cam2_box.setText("")
        self.cam2_box.setObjectName("cam2_box")
        self.cam4_box = QtWidgets.QLabel(self.tab_2)
        self.cam4_box.setGeometry(QtCore.QRect(20, 570, 330, 160))
        self.cam4_box.setText("")
        self.cam4_box.setObjectName("cam4_box")
        self.cam6_box = QtWidgets.QLabel(self.tab_2)
        self.cam6_box.setGeometry(QtCore.QRect(420, 200, 330, 160))
        self.cam6_box.setText("")
        self.cam6_box.setObjectName("cam6_box")
        self.cam5_box = QtWidgets.QLabel(self.tab_2)
        self.cam5_box.setGeometry(QtCore.QRect(420, 10, 330, 160))
        self.cam5_box.setText("")
        self.cam5_box.setObjectName("cam5_box")
        self.cam7_box = QtWidgets.QLabel(self.tab_2)
        self.cam7_box.setGeometry(QtCore.QRect(420, 360, 330, 160))
        self.cam7_box.setText("")
        self.cam7_box.setObjectName("cam7_box")
        self.cam8_box = QtWidgets.QLabel(self.tab_2)
        self.cam8_box.setGeometry(QtCore.QRect(420, 560, 330, 160))
        self.cam8_box.setText("")
        self.cam8_box.setObjectName("cam8_box")
        self.subtab2_widget = QtWidgets.QWidget(self.tab_2)
        self.subtab2_widget.setGeometry(QtCore.QRect(0, 10, 971, 731))
        self.subtab2_widget.setObjectName("subtab2_widget")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.subtab2_widget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, 981, 731))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.subtab2_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.subtab2_Layout.setContentsMargins(0, 0, 0, 0)
        self.subtab2_Layout.setObjectName("subtab2_Layout")
        self.tabWidget.addTab(self.tab_2, "")
        self.right_Layout.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.exit_Button = QtWidgets.QPushButton(Form)
        self.exit_Button.setGeometry(QtCore.QRect(30, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.exit_Button.setFont(font)
        self.exit_Button.setObjectName("exit_Button")
        self.min_Button = QtWidgets.QPushButton(Form)
        self.min_Button.setGeometry(QtCore.QRect(70, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.min_Button.setFont(font)
        self.min_Button.setObjectName("min_Button")
        self.info_widget = QtWidgets.QWidget(Form)
        self.info_widget.setGeometry(QtCore.QRect(10, 690, 191, 111))
        self.info_widget.setObjectName("info_widget")
        self.window_widget = QtWidgets.QWidget(Form)
        self.window_widget.setGeometry(QtCore.QRect(30, 30, 81, 41))
        self.window_widget.setObjectName("window_widget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.window_widget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 81, 41))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.window_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.window_Layout.setContentsMargins(0, 0, 0, 0)
        self.window_Layout.setObjectName("window_Layout")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 690, 191, 111))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.info_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.info_Layout.setContentsMargins(0, 0, 0, 0)
        self.info_Layout.setObjectName("info_Layout")
        self.choose_id = QtWidgets.QLineEdit(Form)
        self.choose_id.setGeometry(QtCore.QRect(50, 380, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.choose_id.setFont(font)
        self.choose_id.setObjectName("choose_id")
        self.label5 = QtWidgets.QLabel(Form)
        self.label5.setGeometry(QtCore.QRect(50, 350, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label5.setFont(font)
        self.label5.setObjectName("label5")
        self.main_widget = QtWidgets.QWidget(Form)
        self.main_widget.setGeometry(QtCore.QRect(10, 20, 191, 671))
        self.main_widget.setObjectName("main_widget")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.main_widget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, 191, 671))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.main_Layout = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.main_Layout.setContentsMargins(0, 0, 0, 0)
        self.main_Layout.setObjectName("main_Layout")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label1.setText(_translate("Form", "Camera"))
        self.cam_num.setCurrentText(_translate("Form", "1"))
        self.cam_num.setItemText(0, _translate("Form", "1"))
        self.cam_num.setItemText(1, _translate("Form", "2"))
        self.cam_num.setItemText(2, _translate("Form", "3"))
        self.cam_num.setItemText(3, _translate("Form", "4"))
        self.label2.setText(_translate("Form", "Start Frame"))
        self.startFrame.setItemText(0, _translate("Form", "0"))
        self.label3.setText(_translate("Form", "End Frame"))
        self.endFrame.setItemText(0, _translate("Form", "100"))
        self.endFrame.setItemText(1, _translate("Form", "5010"))
        self.okButton.setText(_translate("Form", "OK"))
        self.startButton.setText(_translate("Form", "Start"))
        self.stopButton.setText(_translate("Form", "Stop"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.exit_Button.setText(_translate("Form", "X"))
        self.min_Button.setText(_translate("Form", "-"))
        self.label5.setText(_translate("Form", "Choose ID"))

import resource_rc
